#include "nsISupports.idl"


[scriptable, uuid(07f5f6e0-6f49-11df-be2b-0800200c9a66)]
interface jilDataNetworkConnectionTypes : nsISupports
{
  attribute string BLUETOOTH;
  attribute string EDGE;
  attribute string EVDO;
  attribute string GPRS;
  attribute string IRDA;
  attribute string LTE;
  attribute string ONEXRTT;
  attribute string WIFI;
};