#include "jilService.idl"

#include "jilCamera.idl"
#include "jilAudioPlayer.idl"
#include "jilVideoPlayer.idl"


[scriptable, uuid(300a4b90-be91-11de-8a39-0800200c9a66)]
interface jilMultimedia : jilService
{
  attribute jilCamera Camera;
  attribute jilAudioPlayer AudioPlayer;
  attribute jilVideoPlayer VideoPlayer;

  attribute boolean isAudioPlaying;
  attribute boolean isVideoPlaying;

  long getVolume();
  void stopAll();

  void setAudioPlaying(in boolean isPlaying);
};