#include "nsISupports.idl"


[scriptable, uuid(f170f980-be8e-11de-8a39-0800200c9a66)]
interface jilAccelerometerInfo : nsISupports
{
  attribute double xAxis;
  attribute double yAxis;
  attribute double zAxis;
};