#include "nsISupports.idl"

[scriptable, uuid(46df8810-c3f2-11de-8a39-0800200c9a66)]
interface jilEmulatedWidget : nsISupports
{
  attribute string id;
  attribute string version;
  attribute long widgetHeight;
  attribute long widgetWidth;
  attribute long maxHeight;
  attribute long maxWidth;
  attribute boolean billingFlag;
  attribute string iconSrc;
  attribute string contentSrc;
  attribute string name;
  attribute string description;
  attribute string license;
  attribute string author;
  attribute string authorEmail;
  attribute string baseUrl;
  attribute long internalId;
};